apiVersion: apps/v1
kind: Deployment
metadata:
  name: joke-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: joke-app
  template:
    metadata:
      labels:
        app: joke-app
    spec:
      containers:
      - name: joke-app
        image: image_tag
        imagePullPolicy: Always
        ports:
        - containerPort: 5000