apiVersion: apps/v1
kind: Deployment
metadata:
  name: joke-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joke-app
  template:
    metadata:
      labels:
        app: joke-app
    spec:
      containers:
      - name: joke-app
        image: jokeapp.azurecr.io/joke-app:__TAG__
        imagePullPolicy: Always
        ports:
        - containerPort: 5000