apiVersion: apps/v1
kind: Deployment
metadata:
  name: joke-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: joke-app
  template:
    metadata:
      labels:
        app: joke-app
    spec:
      containers:
      - name: joke-app
        image: sachinacr.azurecr.io/joke-app:latest
        ports:
        - containerPort: 5000
